### PR TITLE
Add Paul Tol color scales

### PR DESCRIPTION
**Pull request by jmlondon**
This adds basic support for color scales based on [Paul Tol's Colour Schemes](https://personal.sron.nl/~pault/colourschemes.pdf) for qualitative data. I based the approach off the way the Stephen Few colors and scale functions were specified and tried to make sure things were consistent with the other scales and themes. The documentation and examples have been updated as well.

There is no theme specified, just color scales.

I could not find any explicit declaration of license on Paul Tol's site so have reached out to him via email to confirm there are no issues with incorporating these color schemes into ggthemes.

### CODE REVIEW

**Comment by jrnold** [comment]
Thanks! I hadn't seen that color theme before. 

I think that `ptol_palette()` and the `scales` should not take a separate 'palette' arguments for each number of colors. This will be implied by the argument given to the function returned by palette. If for some reason, a user wanted to use a subset of one of the palettes, they could get it by running `scale_color_manual(pal_ptol(10)[1:5])`.

The diverging and sequential scales mentioned in that paper appear to be from Color Brewer, but those available directly from **RColorBrewer** are limited to a number of values, while Tol gives an equation to impute between them. And the rainbow palette appears to be new. Would you want to add those?

**Comment by jmlondon** [comment]
happy to contribute

I'm having a hard time following what you mean by " `ptol_pal()` and `scales` should not take a separate 'palette' argument for each number of colors. I based my approach on the `tableau.R` functions, so there's probably some detail I'm just not grasping.

That said, while exploring the options and thinking about what you might be referring to, I realized that things could be simplified. Instead of specifying the palette name, we can just specify the number of colors (n) and avoid all of the 'ptol1_qual', 'ptol2_qual',... . I don't think that's what you were suggesting/referring to, but it did help me find a simpler approach.

Is there a way to detect the number of levels so it would auto-magically pick the palette that corresponds to the number of levels based on the colour parameter? I tried to poke around for an example or path and couldn't figure it out.

Regarding the other scales Paul Tol presents, I decided not to include the RColorBrewer based sequential palettes to avoid duplication/confusion. If you think providing a function for imputing between those is worth the effort, I would be supportive. The rainbow palettes could be easily incorporated but I chose not to include them because Paul (and others) discourage the use of rainbow palettes.

**Comment by jrnold** [comment]
Sorry for the ambiguity. The palette function returns a function that takes a single argument, `n`. So I rewrote `ptol_pal` so it would be called like `ptol_pal()(5)`. This also means that the scales do not need an `n` argument.  These changes are now in `master`. I'll put it up on CRAN after I handle a couple more issues.

I'm no fan of rainbow palettes, but since he came up with one that sucks the least, it would be useful to have it. If you're interested submit another pull request.

If you ever get over to UW say hi. I'm in political science and CSSS (and currently run the CSSS seminar series)

**Comment by jmlondon** [comment]
Ah yes, the ol' function that returns a function. Thanks for taking the time to fix things up. 

If I can find some time, I'll add the rainbow colors in following the same approach and open a new pull request.

I'll definitely reach out the next time I have some time on campus (we are hosting the Int'l Statistical Ecology conference on the HUB the last week in June). Would be good to make some additional connections on campus.

**Comment by jrnold** [comment]
Thanks for letting me know about this article and the palettes. Getting informed of these things is a nice externality of maintaining this package.

**Pull request merged**
