### PR TITLE
Typo fix: theme_wsj is based on The Wall Street Journal and not on The Economist

### PR DESCRIPTION
**Pull request by sainathadapa**
Note: I couldn't build the vignettes from source. Code was failing in examples.Rmd. So, I edited the README.md manually.

### CODE REVIEW

**Comment by jrnold** [comment]
Thanks. It's fixed in the development version. The code is failing because at the moment the development version of **ggthemes** only works with the development version of **ggplot2** and not the version on CRAN (v1.1.0 of ggplot2 will be uploaded next month has changes in the way it handles scales and geoms that is backwards incompatible).

**Comment by sainathadapa** [comment]
I guessed it and installed the latest github version. I still couldn't build the vignettes. May be there are some very recent breaking changes in ggplot.

**Comment by jrnold** [comment]
Could you provide an error message?

**Comment by sainathadapa** [comment]
```
> devtools::build()
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD build '/home/sainath/ggthemes'  \
  --no-resave-data --no-manual 

* checking for file ‘/home/sainath/ggthemes/DESCRIPTION’ ... OK
* preparing ‘ggthemes’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
* saving partial Rd database
* creating vignettes ... ERROR
processing file: ./children/intro.Rmd
processing file: ./children/examples.Rmd
Quitting from lines 15-19 (./children/examples.Rmd) 
Quitting from lines 24-27 (./children/examples.Rmd) 
Error: processing vignette 'ggthemes.Rmd' failed with diagnostics:
unused argument (geom_params = list(sides = sides, fun_min = fun_min, fun_max = fun_max))
Execution halted
Error: Command failed (1)
```

**Comment by jrnold** [comment]
I'll look into it

**Comment by sainathadapa** [comment]
Thanks.

**Comment by jrnold** [comment]
Looks like there's been some more changes to ggplot2. I'll need to rewrite a few things to make it compatible again.

**Pull request closed without merging**
