### PR TITLE
Changes in upcoming ggplot2 version

### PR DESCRIPTION
**Pull request by teunbrand**
Hi there,

We have been preparing a new release of ggplot2 and during a reverse dependency check, it became apparent that the prospective ggplot2 3.5.0 would break ggthemes.

As a brief summary, we've modified the scale's `call` field to hold a more informative call for the use in error messages and warnings. Unfortunately, this means that the scale equality assumptions in ggthemes no longer hold. This PR does two things:

* It updates the tests to check for scale equality that doesn't depend on the `call` field.
* It pre-emptively replaces recently deprecated theme arguments. This isn't strictly necessary as there is a fallback, but it reduces the warnings a bit.

To test the code changes with the release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The release of ggplot2 3.5.0 is scheduled for the 12th of February. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588. We hope that this PR might help ggthemes get out a fix if necessary.

### CODE REVIEW

**Comment by teunbrand** [comment]
This is just a kind reminder that the release is scheduled soon.

**Comment by jrnold** [comment]
Thanks! I'll get this merged.

Do this changes require updating the minimum version of ggplot2 in the dependencies?

**Review by jrnold — COMMENTED** [review]
Can you rebase against main and update `NEWS.md` with a description of the changes?

**Comment by jrnold** [comment]
Thanks! Merged. Today, I'll be fixing up misc issues that have arisen over time. I'll submit a new version to CRAN by eod pacific time.

**Comment by jrnold** [comment]
By the way - I'm looking for someone to take over as maintainer of ggthemes. Do you know anyone?

**Pull request merged**
